"""Remove some api key nullables

Revision ID: 5431fd03df08
Revises: e0982b99b75
Create Date: 2015-12-09 01:13:41.017747

"""

# revision identifiers, used by Alembic.
revision = '5431fd03df08'
down_revision = 'e0982b99b75'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('api_key', 'used_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'used_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('api_key', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###
