"""Organization user relationship

Revision ID: 66bc67e7a8d5
Revises: 5431fd03df08
Create Date: 2015-12-19 22:42:38.290927

"""

# revision identifiers, used by Alembic.
revision = '66bc67e7a8d5'
down_revision = '5431fd03df08'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_user',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('administrator', 'editor'), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_user_created_at'), 'organization_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_user_organization_id'), 'organization_user', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_user_updated_at'), 'organization_user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_organization_user_user_id'), 'organization_user', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_user_user_id'), table_name='organization_user')
    op.drop_index(op.f('ix_organization_user_updated_at'), table_name='organization_user')
    op.drop_index(op.f('ix_organization_user_organization_id'), table_name='organization_user')
    op.drop_index(op.f('ix_organization_user_created_at'), table_name='organization_user')
    op.drop_table('organization_user')
    ### end Alembic commands ###
