"""Make panel times optional

Revision ID: da7863e6260a
Revises: 669c3d46d770
Create Date: 2015-12-27 15:45:00.597975

"""

# revision identifiers, used by Alembic.
revision = 'da7863e6260a'
down_revision = '669c3d46d770'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panel', 'ends_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('panel', 'starts_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panel', 'starts_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('panel', 'ends_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###
