"""Venues

Revision ID: e0982b99b75
Revises: 4d95a2959950
Create Date: 2015-12-06 02:33:37.009536

"""

# revision identifiers, used by Alembic.
revision = 'e0982b99b75'
down_revision = '4d95a2959950'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('slug', sa.Unicode(length=255), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_venue_created_at'), 'venue', ['created_at'], unique=False)
    op.create_index(op.f('ix_venue_organization_id'), 'venue', ['organization_id'], unique=False)
    op.create_index(op.f('ix_venue_updated_at'), 'venue', ['updated_at'], unique=False)
    op.add_column(u'panel', sa.Column('venue_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_panel_venue_id'), 'panel', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'panel', 'venue', ['venue_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'panel', type_='foreignkey')
    op.drop_index(op.f('ix_panel_venue_id'), table_name='panel')
    op.drop_column(u'panel', 'venue_id')
    op.drop_index(op.f('ix_venue_updated_at'), table_name='venue')
    op.drop_index(op.f('ix_venue_organization_id'), table_name='venue')
    op.drop_index(op.f('ix_venue_created_at'), table_name='venue')
    op.drop_table('venue')
    ### end Alembic commands ###
